### PR TITLE
Bring Galacticraft, Tardis/Dalek mod and Dark Core to current

### LINKED ISSUE #22: Update Tardis mod to fix bugs
Tardis mod was updated to v0.99 on Aug 14, 2015 ([Forum link](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod-updated-to-v0-99-on-13-08-2015?comment=1107)). The fixes list include the bug that bugs me. Namely, Temporal Dirt block disappears when a tree or an Ender Lily grows on it (dropping an extra sapling for a tree, or two lily seeds for a lily).

### PR DESCRIPTION
**Pull request by NolanSyKinsley**
Nothing blew up as far as I can tell.

- Players will get a warning about Galacticraft oil/fuel tiles missing. This will remove any placed fuel/oil liquid in the world but filled canisters/tanks and fuel/oil in machines are safe. (Galacticraft changed the fuel/oil tile blocks for compatibility with other mods)

- fixed the default maps, just replaced the level.dat with an updated/sanitized one to prevent missing tile error message.

Closes #22

### CODE REVIEW

**Comment by drz2k** [comment]
I need to check that oil thingy, then your pull request is welcome as allways :)

**Comment by SirWilli** [comment]
As the issue with tier 3 rockets got fixed it should be fine to update galacticraft.

**Comment by NolanSyKinsley** [comment]
Oh, I just realized something, on the update to galacticraft it will default to meteor damage being disabled, the config will have to be genned then set to enable.

**Comment by drz2k** [comment]
Started testing. The maps templates start at night, instant player ownage :D

**Comment by NolanSyKinsley** [comment]
Oh, that is not right... I though I had just loaded them and instantly saved, I might have over sanitized the level.dat and removed the time of day.

**Comment by SirWilli** [comment]
You should merge the new + repo level.dat so only the item ID's get 
updated and no other data.

Am 18.10.2015 um 22:27 schrieb NolanSyKinsley:

**Comment by NolanSyKinsley** [comment]
If the repo level.dat is used players will get a missing tile/item warning on first load. If you want me to leave the changes to the level.dat up to you I will close this issue and open an new PR sans the changes to the level.dat.

**Comment by SirWilli** [comment]
What I mean is to edit the level.dat files with NBTExplorer and move 
only the item data stuff over instead of the complete file

**Comment by NolanSyKinsley** [comment]
Oh, I couldn't find a way with NBT explorer to copy the item data from one level.dat to the other, it opened the second level.dat into a separate window and the copy/paste function did not work between them.

**Comment by Slind14** [comment]
Try a bit more, it should work just fine.

**Comment by Slind14** [comment]
all those mods were updated on the secondary branch to the latest version as of state.

**Pull request closed without merging**
