### PR TITLE
Adds Storage Drawers and Super Crafting Frames

### PR DESCRIPTION
**Pull request by NolanSyKinsley**
I don't know how open you are to feature/mod requests, but I figured it might help if I did the legwork. I have been using these two mods in my own world because with Refined Relocation and JABBA installed I consider them indispensable. 

The two mods added are Storage Drawers and Super Crafting Frames. I know the importance of keeping the modpack slim(I only have 4gb of memory myself), these two only add ~130kb of extra size to it and they have minimal memory footprint. 

Storage Drawers highly integrates with Refined Relocation's sorting system, but also has a controller and controller slave, which are blocks that you can interact with and access the whole system using pipes for insertion or extraction, and more importantly you can plop a Super Crafting frame down on them and it instantly becomes a very very powerful poor man's AE crafting system.

The controller, controller slave and compacting drawers I found too powerful for T1 if accessible in large numbers. I changed the recipes to use 2 desh each but set a quest to receive one each of the controller and slave. Making more controllers or slaves, and obtaining the compacting drawer is delayed until T2.

Super crafting frame recipe may need adjusting.

- These mods should not affect game/tech progression, they just help take the tedium out of crafting and compact/clean up the look of storage areas.

- 3 Quests added to Storage Solution page for Storage Drawers rewarding with a controller and slave, keys for locking, and sorting upgrades.

- 1 Quest added in the Why do all the work page for the Super Crafting Frame rewarding 5 super item frames and 1 super void frame

Note: if #25 and this PR are to be accepted I will need to modify this PR as it changes the questbook and I did both changes from the same commit on their own branches.

### CODE REVIEW

**Comment by SirWilli** [comment]
I don't like crafting frames as they have some dupe bugs and you can't protect storage drawers on servers except this got fixed.

**Comment by NolanSyKinsley** [comment]
I believe all of the dupe bugs with super crafting on JABBA frames were fixed back in February. I know that JadedCat is really really careful with mods that can have any possible dupe bugs and they are included in her AS2 modpack. I will scour around and see if I can find any non fixed dupe bugs with the crafting frames.

**Comment by Slind14** [comment]
@drz2k what's your opinion on this matter?

**Comment by 062904** [comment]
i also think this would be quite neat to have

**Comment by SirWilli** [comment]
Closing this I assume this will not be implemented

**Pull request closed without merging**
