### PR TITLE
Nerf tardis key LP

### PR DESCRIPTION
**Pull request by cblair91**
Full inventory of regen 2 potions, while attempting to fight mobs and sacrifice life = near impossible.

Nerfing it to 50k LP still makes it hard, yet actually possible.

### CODE REVIEW

**Comment by PLASMAchicken** [comment]
Use penicilin

**Comment by cblair91** [comment]
Same as using a regen 2 potion >.>

**Comment by PLASMAchicken** [comment]
penicilin you can use endless


2016-02-20 17:21 GMT+01:00 Kris <notifications@github.com>:

**Comment by drz2k** [comment]
Ive seen many do it with minechem liquids poured and a battle suit or even less on first try. So since this is kinda the final wall in this pack, its fine as it is. Two guys made through it on first try after we first published the update with the temple.

So :
1. Do you wear a battlesuit and use a good weapon like the eviscerator?
2. Do you pour minechem liquids to take use of their effects?

**Comment by cblair91** [comment]
Suggestions taken back onboard ;p Battlesuit, eviscerator and penicilin ;D thanks you.

**Comment by drz2k** [comment]
Good luck :)

A ranged weapon is also a good alternative but the eviscerator is just ... brutal ... the toy of choice for a rambo.

**Pull request closed without merging**
